baseURL: https://www.stefanheyder.netlify.com
title: Stefans blog
theme: etch
languageCode: en-US
enableInlineShortcodes: yes
pygmentsCodeFences: yes
pygmentsUseClasses: yes
params:
  copyright: Copyright © 2022 Stefan
  dark: auto
  description: Crossfit & Stats
  highlight: yes
menu:
  main:
    - identifier: posts
      name: posts
      title: posts
      url: /
      weight: 10
    - identifier: about
      name: about
      title: about
      url: /about/
      weight: 20
permalinks:
  posts: /:title/
markup:
  goldmark:
    renderer:
      unsafe: yes
  tableOfContents:
    ordered: yes
ignoreErrors: ["error-missing-instagram-accesstoken"]
